development:
  adapter: postgresql
  encoding: unicode
  database: jcobb_designs_development

test:
  adapter: postgresql
  encoding: unicode
  database: jcobb_designs_test

production:
  adapter: postgresql
  encoding: unicode
  database: jcobb_designs_production
